-- Create CITY table
CREATE TABLE CITY (
    ID INT PRIMARY KEY,
    NAME VARCHAR(17),
    COUNTRYCODE VARCHAR(3),
    DISTRICT VARCHAR(20),
    POPULATION INT
);

-- Create STATION table
CREATE TABLE STATION (
    ID INT PRIMARY KEY,
    CITY VARCHAR(21),
    STATE VARCHAR(2),
    LAT_N DECIMAL(10,4),
    LONG_W DECIMAL(10,4)
);

-- Create OCCUPATIONS table
CREATE TABLE OCCUPATIONS (
    NAME VARCHAR(50),
    OCCUPATION VARCHAR(20)
);

-- Create TRIANGLES table
CREATE TABLE TRIANGLES (
    A INT,
    B INT,
    C INT
);

-- Create STUDENTS table
CREATE TABLE STUDENTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    MARKS INT
);

-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    SALARY INT
);

-- Create COUNTRY table
CREATE TABLE COUNTRY (
    CODE VARCHAR(3) PRIMARY KEY,
    NAME VARCHAR(44),
    CONTINENT VARCHAR(13)
);