-- Insert data into CITY table
INSERT INTO CITY VALUES (1, 'New York', 'USA', 'New York', 8550405);
INSERT INTO CITY VALUES (2, 'Los Angeles', 'USA', 'California', 3971883);
INSERT INTO CITY VALUES (3, 'Chicago', 'USA', 'Illinois', 2720546);
INSERT INTO CITY VALUES (4, 'Houston', 'USA', 'Texas', 2296224);
INSERT INTO CITY VALUES (5, 'Tokyo', 'JPN', 'Tokyo', 13929286);
INSERT INTO CITY VALUES (6, 'Osaka', 'JPN', 'Osaka', 2691742);
INSERT INTO CITY VALUES (7, 'Kyoto', 'JPN', 'Kyoto', 1474570);
INSERT INTO CITY VALUES (8, 'London', 'GBR', 'England', 8908081);
INSERT INTO CITY VALUES (9, 'Paris', 'FRA', 'Île-de-France', 2148271);
INSERT INTO CITY VALUES (10, 'Berlin', 'DEU', 'Berlin', 3669491);
INSERT INTO CITY VALUES (1661, 'Berlin', 'DEU', 'Berlin', 3669491);

-- Insert data into STATION table
INSERT INTO STATION VALUES (1, 'Phoenix', 'AZ', 33.4484, 112.0740);
INSERT INTO STATION VALUES (2, 'Sacramento', 'CA', 38.5816, 121.4944);
INSERT INTO STATION VALUES (3, 'Denver', 'CO', 39.7392, 104.9903);
INSERT INTO STATION VALUES (4, 'Atlanta', 'GA', 33.7490, 84.3880);
INSERT INTO STATION VALUES (5, 'Chicago', 'IL', 41.8781, 87.6298);
INSERT INTO STATION VALUES (6, 'Boston', 'MA', 42.3601, 71.0589);
INSERT INTO STATION VALUES (7, 'Detroit', 'MI', 42.3314, 83.0458);
INSERT INTO STATION VALUES (8, 'Minneapolis', 'MN', 44.9778, 93.2650);
INSERT INTO STATION VALUES (9, 'New York', 'NY', 40.7128, 74.0060);
INSERT INTO STATION VALUES (10, 'Portland', 'OR', 45.5051, 122.6750);
INSERT INTO STATION VALUES (11, 'Austin', 'TX', 30.2672, 97.7431);
INSERT INTO STATION VALUES (12, 'Seattle', 'WA', 47.6062, 122.3321);
INSERT INTO STATION VALUES (13, 'A', 'TX', 30.2672, 97.7431);
INSERT INTO STATION VALUES (14, 'Amritsar', 'TX', 30.2672, 97.7431);
INSERT INTO STATION VALUES (15, 'Z', 'TX', 30.2672, 97.7431);
INSERT INTO STATION VALUES (16, 'Zephyr', 'TX', 30.2672, 97.7431);

-- Insert data into OCCUPATIONS table
INSERT INTO OCCUPATIONS VALUES ('Samantha', 'Doctor');
INSERT INTO OCCUPATIONS VALUES ('Julia', 'Actor');
INSERT INTO OCCUPATIONS VALUES ('Maria', 'Actor');
INSERT INTO OCCUPATIONS VALUES ('Meera', 'Singer');
INSERT INTO OCCUPATIONS VALUES ('Ashely', 'Professor');
INSERT INTO OCCUPATIONS VALUES ('Ketty', 'Professor');
INSERT INTO OCCUPATIONS VALUES ('Christeen', 'Professor');
INSERT INTO OCCUPATIONS VALUES ('Jane', 'Actor');
INSERT INTO OCCUPATIONS VALUES ('Jenny', 'Doctor');
INSERT INTO OCCUPATIONS VALUES ('Priya', 'Singer');

-- Insert data into TRIANGLES table
INSERT INTO TRIANGLES VALUES (10, 10, 10);
INSERT INTO TRIANGLES VALUES (11, 11, 11);
INSERT INTO TRIANGLES VALUES (30, 30, 30);
INSERT INTO TRIANGLES VALUES (20, 20, 10);
INSERT INTO TRIANGLES VALUES (20, 10, 20);
INSERT INTO TRIANGLES VALUES (10, 20, 20);
INSERT INTO TRIANGLES VALUES (5, 3, 4);
INSERT INTO TRIANGLES VALUES (3, 4, 5);
INSERT INTO TRIANGLES VALUES (10, 15, 20);
INSERT INTO TRIANGLES VALUES (20, 10, 15);
INSERT INTO TRIANGLES VALUES (20, 30, 10);
INSERT INTO TRIANGLES VALUES (10, 5, 4);

-- Insert data into STUDENTS table
INSERT INTO STUDENTS VALUES (1, 'Ashley', 81);
INSERT INTO STUDENTS VALUES (2, 'Samantha', 75);
INSERT INTO STUDENTS VALUES (3, 'Julia', 76);
INSERT INTO STUDENTS VALUES (4, 'Belvet', 84);
INSERT INTO STUDENTS VALUES (5, 'Britney', 91);
INSERT INTO STUDENTS VALUES (6, 'Kristeen', 79);
INSERT INTO STUDENTS VALUES (7, 'Dyana', 73);
INSERT INTO STUDENTS VALUES (8, 'Jenny', 97);
INSERT INTO STUDENTS VALUES (9, 'Christene', 88);
INSERT INTO STUDENTS VALUES (10, 'Meera', 67);
INSERT INTO STUDENTS VALUES (11, 'Priya', 68);
INSERT INTO STUDENTS VALUES (12, 'Priyanka', 99);

-- Insert data into EMPLOYEE table
INSERT INTO EMPLOYEE VALUES (1, 'Jason', 3400);
INSERT INTO EMPLOYEE VALUES (2, 'Ashley', 5000);
INSERT INTO EMPLOYEE VALUES (3, 'Julia', 2700);
INSERT INTO EMPLOYEE VALUES (4, 'Maria', 4000);
INSERT INTO EMPLOYEE VALUES (5, 'Meera', 3500);
INSERT INTO EMPLOYEE VALUES (6, 'Priya', 2100);
INSERT INTO EMPLOYEE VALUES (7, 'Samantha', 5500);
INSERT INTO EMPLOYEE VALUES (8, 'Ketty', 4100);
INSERT INTO EMPLOYEE VALUES (9, 'James', 6800);
INSERT INTO EMPLOYEE VALUES (10, 'Jane', 2900);

-- Insert data into COUNTRY table
INSERT INTO COUNTRY VALUES ('USA', 'United States', 'North America');
INSERT INTO COUNTRY VALUES ('CAN', 'Canada', 'North America');
INSERT INTO COUNTRY VALUES ('MEX', 'Mexico', 'North America');
INSERT INTO COUNTRY VALUES ('BRA', 'Brazil', 'South America');
INSERT INTO COUNTRY VALUES ('ARG', 'Argentina', 'South America');
INSERT INTO COUNTRY VALUES ('GBR', 'United Kingdom', 'Europe');
INSERT INTO COUNTRY VALUES ('FRA', 'France', 'Europe');
INSERT INTO COUNTRY VALUES ('DEU', 'Germany', 'Europe');
INSERT INTO COUNTRY VALUES ('ITA', 'Italy', 'Europe');
INSERT INTO COUNTRY VALUES ('ESP', 'Spain', 'Europe');
INSERT INTO COUNTRY VALUES ('CHN', 'China', 'Asia');
INSERT INTO COUNTRY VALUES ('JPN', 'Japan', 'Asia');
INSERT INTO COUNTRY VALUES ('IND', 'India', 'Asia');
INSERT INTO COUNTRY VALUES ('AUS', 'Australia', 'Oceania');
INSERT INTO COUNTRY VALUES ('NZL', 'New Zealand', 'Oceania');